# -*- coding: utf-8 -*-
"""una_linea_html_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IvuFH2oPnpyyTWBnTJacIzuhuv-vF712
"""

# usar la pagina de abajo y si aun le falta usar este codigo
# https://htmlcompressor.com/compressor/

html = input("Ingrese html para hacer una linea: ")
"".join(html.replace("\"", "'").split("\n"))